# Generated by Django 4.2.13 on 2024-06-02 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock_product', '0001_initial'),
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(max_length=255)),
                ('total_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.client')),
            ],
        ),
        migrations.CreateModel(
            name='OrderSaleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_sale.ordersale')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_product.product')),
            ],
        ),
    ]
