# Generated by Django 4.2.13 on 2024-06-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_sale', '0002_alter_ordersaledetail_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersaledetail',
            name='total_detail',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ordersale',
            name='state',
            field=models.CharField(choices=[('INPROGRESS', 'INPROGRESS'), ('COMPLETED', 'COMPLETED')], default='INPROGRESS', max_length=10),
        ),
    ]
