# Generated by Django 4.2.13 on 2024-06-05 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_supplier', '0002_alter_ordersupplier_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersupplierdetail',
            name='total_purchase',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
